[versions]
aboutLicenses = "11.2.2"
androidx-activity = "1.9.1"
androidx-appcompat = "1.7.0"
agp = "8.5.2"
circuit = "0.23.1"
compose-cupertino = "0.1.0-alpha04"
compose-jb = "1.6.11"
jdk = "21"
jvmTarget = "11"
kotlin = "2.0.10"
kotlinx-coroutines = "1.9.0-RC.2"
ktfmt = "0.50"
ktor = "2.3.12"
okio = "3.9.0"
spotless = "6.23.3"
sqldelight = "2.0.2"

[plugins]
aboutLicenses = { id = "com.mikepenz.aboutlibraries.plugin", version.ref = "aboutLicenses" }
agp-application = { id = "com.android.application", version.ref = "agp" }
bugsnag = { id = "com.bugsnag.android.gradle", version = "8.1.0" }
buildConfig = { id = "com.github.gmazzo.buildconfig", version = "5.3.5" }
compose = { id = "org.jetbrains.compose", version.ref = "compose-jb" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-plugin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-plugin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
sqldelight = { id = "app.cash.sqldelight", version.ref = "sqldelight" }

[libraries]
aboutLicenses = { module = "com.mikepenz:aboutlibraries-compose-m3", version.ref = "aboutLicenses" }
androidx-appCompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-compose-integration-activity = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-splash = "androidx.core:core-splashscreen:1.0.1"
# Utilities for local storage dirs on Desktop
# https://github.com/harawata/appdirs
appDirs = "net.harawata:appdirs:1.2.2"
bugsnag-android = "com.bugsnag:bugsnag-android:6.7.0"
circuit-foundation = { module = "com.slack.circuit:circuit-foundation", version.ref = "circuit" }
circuit-overlay = { module = "com.slack.circuit:circuit-overlay", version.ref = "circuit" }
circuitx-overlays = { module = "com.slack.circuit:circuitx-overlays", version.ref = "circuit" }
circuitx-gestureNav = { module = "com.slack.circuit:circuitx-gesture-navigation", version.ref = "circuit" }
compose-cupertino-adaptive = { module = "io.github.alexzhirkevich:cupertino-adaptive", version.ref = "compose-cupertino" }
compose-cupertino-native = { module = "io.github.alexzhirkevich:cupertino-native", version.ref = "compose-cupertino" }
compose-material-icons = { module = "org.jetbrains.compose.material:material-icons-core", version.ref = "compose-jb" }
compose-material-material3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "compose-jb" }
# Tooling support (Previews, etc.)
compose-ui-tooling = { module = "org.jetbrains.compose.ui:ui-tooling", version.ref = "compose-jb" }
compose-ui-tooling-data = { module = "org.jetbrains.compose.ui:ui-tooling-data", version.ref = "compose-jb" }
compose-ui-tooling-preview = { module = "org.jetbrains.compose.ui:ui-tooling-preview", version.ref = "compose-jb" }
coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
desugarJdkLibs = "com.android.tools:desugar_jdk_libs:2.0.4"
kotlinx-datetime = "org.jetbrains.kotlinx:kotlinx-datetime:0.6.0"
kotlinx-immutable = "org.jetbrains.kotlinx:kotlinx-collections-immutable:0.3.7"
kotlin-bom = { module = "org.jetbrains.kotlin:kotlin-bom", version.ref = "kotlin" }
kotlin-plugins-bom = { module = "org.jetbrains.kotlin:kotlin-gradle-plugins-bom", version.ref = "kotlin" }
ktor-client = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-engine-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-client-engine-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
lints-compose = "com.slack.lint.compose:compose-lint-checks:1.3.1"
okio = { module = "com.squareup.okio:okio", version.ref = "okio" }
sqldelight-driver-android = { module = "app.cash.sqldelight:android-driver", version.ref = "sqldelight" }
sqldelight-driver-jdbc = { module = "app.cash.sqldelight:sqlite-driver", version.ref = "sqldelight" }
sqldelight-driver-native = { module = "app.cash.sqldelight:native-driver", version.ref = "sqldelight" }
sqldelight-async = { module = "app.cash.sqldelight:async-extensions", version.ref = "sqldelight" }
sqldelight-coroutines = { module = "app.cash.sqldelight:coroutines-extensions", version.ref = "sqldelight" }
